### ISSUE TITLE
Tagging releases

### ISSUE THREAD

**Issue by SnarkBoojum** [benjamn/private#10]
When you bump the npm version, it would be helpful to also tag the release, so tarballs get generated.

I might package private for Debian, if I can lay my hand on a tarball...

**Comment by SnarkBoojum** [comment]
Any news on the matter?

**Comment by SnarkBoojum** [comment]
Please, I would just need a "git tag v0.1.6" followed by "git push --tags" and it's done... Or perhaps github makes it even easier than that...

**Comment by benjamn** [comment]
Done! Sorry for the delay, and I'll try to be better about this in the future (this is one of my older repositories, unfortunately somewhat neglected).
