### ISSUE TITLE
package properties

### ISSUE THREAD

**Issue by skinnybrit51** [benjamn/private#12]
What are these properties for in the package.json file? They are causing issues when I try an point my npm config registry url to a different url.

  "_id": "private@0.1.6",
  "_shasum": "55c6a976d0f9bafb9924851350fe47b9b5fbb7c1",
  "_resolved": "https://registry.npmjs.org/private/-/private-0.1.6.tgz",
  "_from": "https://registry.npmjs.org/private/-/private-0.1.6.tgz"

**Comment by benjamn** [comment]
Those properties are added to `package.json` by `npm` after the package is installed. Notice that they are not present in the source file: https://github.com/benjamn/private/blob/master/package.json
